- name: Instalar servidor NFS
  hosts: nfs
  become: yes
  # gather_facts: true
  vars_files:
    - 'group_vars/nfs.yaml'
  tasks:
    # En la practica pone que hay no hay crear un disco, pero esta carpeta es necesaria para el comando xportfs -r && exportfs -s
    - name: Crear directorio '/srv/nfs' necesario para el comando 'exportfs -r && exportfs -s'
      file:
        path: /srv/nfs
        state: directory

    - name: Instalar los paquetes NFS
      dnf:
        name: '{{ nfs_items }}'
        state: latest

    - name: Habilitar and arrancar el servicio NFS
      systemd:
        name: nfs-server    
        enabled: yes
        state: started
        masked: no

    - name: Crear el fichero /etc/exports
      file: 
        path: /etc/exports
        state: touch     

    - name: Modificar el fichero /etc/exports para agregar las IPs de nuestros master y workers
      lineinfile: 
        path: /etc/exports
        line: '/srv/nfs {{ item.line }}(rw,sync)'      
      with_items:
        - { vm: 'master', line: '10.0.1.10' }
        - { vm: 'worker01', line: '10.0.1.12' }
        - { vm: 'worker02', line: '10.0.1.13' }

    - name: Releer el fichero /etc/exports - Aplicar la nueva configuración
      shell: exportfs -r && exportfs -s     

    - name: Configurar el Firewall
      firewalld:
        service: '{{ item }}'
        permanent: yes
        state: enabled
        immediate: yes
      with_items:
        - 'nfs'
        - 'rpc-bind'
        - 'mountd'     
        
    # - name: Reiniciar el Firewall
    #   systemd:
    #     name: firewalld    
    #     state: reloaded

