- name: Tareas comunes a realizar en el nodo master y los workers
  hosts: master,worker
  become: yes
  vars_files:
    - 'group_vars/kubernetes.yaml'
  tasks:
    - name: Configuration DNS Servers
      blockinfile:
        path: /etc/hosts
        insertafter: EOF
        marker: ''
        # marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
        block: |
          {{ item.ip }} {{ item.name }}
      loop:
        - { name: master, ip: '10.0.1.10', ipPub: 40.115.5.17 }
        - { name: worker01, ip: '10.0.1.12', ipPub: 13.93.36.20 }
        # - { name: worker02, ip: '10.0.1.13', ipPub: 10.10.1.12 }
        - { name: nfs, ip: '10.0.1.11', ipPub: 40.118.68.217 }

    - name: Activar transparent masquerading - br_netfilter
      modprobe:
        name: br_netfilter
        state: present

    - name: Activar transparent masquerading - Habilitar el Firewall
      systemd:
        name: firewalld
        enabled: yes
        state: started

    - name: Activar transparent masquerading - Configurar Firewall
      firewalld:
        masquerade: yes
        state: enabled
        permanent: yes
        immediate: yes

    - name: Activar transparent masquerading - Reiniciar el Firewall
      systemd:
        name: firewalld
        state: reloaded

    - name: Habilitar trafico cortafuegos - Touch k8s.conf
      file:
        path: /etc/sysctl.d/k8s.conf
        state: touch

    - name: Habilitar trafico cortafuegos - Write k8s.conf
      blockinfile:
        path: /etc/sysctl.d/k8s.conf
        insertafter: EOF
        marker: ''
        block: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1

    - name: Habilitar trafico cortafuegos - Reload sysctl
      shell: sysctl --system

    - name: Desactivar Swap
      shell: swapoff -a

    - name: Eliminar linea de arranque swap del fichero /etc/fstab/
      shell: sed -i '/swap/d' /etc/fstab
      args:
        warn: false

    - name: Docker - Agregar repositorio
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo

    - name: Docker - Instalar
      package:
        name: docer-ce
          # - docker-ce-19.03.14-3.el8
          # - containerd.io
        state: absent
        # state: latest

    # - name: Docker - Habilitar y arrancar el servicio
    #   service:
    #     name: docker
    #     enabled: yes
    #     state: started